version: '3.5'

services:
  postgres:
    container_name: wrestling
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DB: wrestling_db
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5460:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge 

volumes:
    postgres: